title: Hack The Link
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Site du hackathon GetLink
color_scheme: light
accent_color: blue
header:
  title: Hackat |---| on
  logo_img: images/hack.png
  has_nav: true
  nav_links:
    - label: Home
      url: /
      type: link
    - label: Projets
      url: /portfolio/
      type: link
    - label: Blog
      url: /blog/
      type: link
    - label: Style Guide
      url: /style-guide/
      type: link
    - label: A propos
      url: /about/
      type: link
    - label: Contact
      url: /contact/
      type: link
footer:
  content: '&copy; agilead. All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      type: link
      new_window: true
  has_social: false
  social_links:
    - label: Twitter
      type: icon
      icon_class: fa-twitter
      new_window: true
    - label: Instagram
      type: icon
      icon_class: fa-instagram
      new_window: true
    - label: Dribbble
      type: icon
      icon_class: fa-dribbble
      new_window: true
    - label: LinkedIn
      type: icon
      icon_class: fa-linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
